package com.dce.business.entity.notice;

import java.util.Date;

import org.hibernate.validator.constraints.NotBlank;

public class NoticeDo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_ys_notice.id
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_ys_notice.title
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	@NotBlank(message = "公告标题不能为空")
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_ys_notice.image
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	private String image;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_ys_notice.author
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_ys_notice.top_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	private Integer topNotice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_ys_notice.remark
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_ys_notice.status
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_ys_notice.create_date
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_ys_notice.create_name
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	private String createName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_ys_notice.update_date
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_ys_notice.update_name
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	private String updateName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_ys_notice.content
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_ys_notice.id
	 * @return  the value of t_ys_notice.id
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_ys_notice.id
	 * @param id  the value for t_ys_notice.id
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_ys_notice.title
	 * @return  the value of t_ys_notice.title
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_ys_notice.title
	 * @param title  the value for t_ys_notice.title
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_ys_notice.image
	 * @return  the value of t_ys_notice.image
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public String getImage() {
		return image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_ys_notice.image
	 * @param image  the value for t_ys_notice.image
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_ys_notice.author
	 * @return  the value of t_ys_notice.author
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_ys_notice.author
	 * @param author  the value for t_ys_notice.author
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_ys_notice.top_notice
	 * @return  the value of t_ys_notice.top_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public Integer getTopNotice() {
		return topNotice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_ys_notice.top_notice
	 * @param topNotice  the value for t_ys_notice.top_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public void setTopNotice(Integer topNotice) {
		this.topNotice = topNotice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_ys_notice.remark
	 * @return  the value of t_ys_notice.remark
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_ys_notice.remark
	 * @param remark  the value for t_ys_notice.remark
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_ys_notice.status
	 * @return  the value of t_ys_notice.status
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_ys_notice.status
	 * @param status  the value for t_ys_notice.status
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_ys_notice.create_date
	 * @return  the value of t_ys_notice.create_date
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_ys_notice.create_date
	 * @param createDate  the value for t_ys_notice.create_date
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_ys_notice.create_name
	 * @return  the value of t_ys_notice.create_name
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public String getCreateName() {
		return createName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_ys_notice.create_name
	 * @param createName  the value for t_ys_notice.create_name
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public void setCreateName(String createName) {
		this.createName = createName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_ys_notice.update_date
	 * @return  the value of t_ys_notice.update_date
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_ys_notice.update_date
	 * @param updateDate  the value for t_ys_notice.update_date
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_ys_notice.update_name
	 * @return  the value of t_ys_notice.update_name
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public String getUpdateName() {
		return updateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_ys_notice.update_name
	 * @param updateName  the value for t_ys_notice.update_name
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public void setUpdateName(String updateName) {
		this.updateName = updateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_ys_notice.content
	 * @return  the value of t_ys_notice.content
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_ys_notice.content
	 * @param content  the value for t_ys_notice.content
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	public void setContent(String content) {
		this.content = content;
	}
}