package com.dce.business.dao.notice;

import com.dce.business.entity.notice.NoticeDo;
import com.dce.business.entity.notice.NoticeDoExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface NoticeDoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ys_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	long countByExample(NoticeDoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ys_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	int deleteByExample(NoticeDoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ys_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);
	
	NoticeDo selectNoticeById(Integer noticeId);
	
	List<NoticeDo> queryListPage(Map<String, Object> param);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ys_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	int insert(NoticeDo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ys_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	int insertSelective(NoticeDo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ys_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	List<NoticeDo> selectByExampleWithBLOBs(NoticeDoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ys_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	List<NoticeDo> selectByExample(NoticeDoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ys_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	NoticeDo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ys_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	int updateByExampleSelective(@Param("record") NoticeDo record, @Param("example") NoticeDoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ys_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") NoticeDo record, @Param("example") NoticeDoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ys_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	int updateByExample(@Param("record") NoticeDo record, @Param("example") NoticeDoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ys_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	int updateByPrimaryKeySelective(NoticeDo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ys_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(NoticeDo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ys_notice
	 * @mbg.generated  Wed Aug 08 21:46:45 CST 2018
	 */
	int updateByPrimaryKey(NoticeDo record);
}