package com.dce.business.entity.etherenum;

import java.util.Date;

public class EthAccountDetailDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_ethereum_account_detail.id
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_ethereum_account_detail.userId
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_ethereum_account_detail.serialNo
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    private String serialno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_ethereum_account_detail.ethAccount
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    private String ethaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_ethereum_account_detail.ethAccountType
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    private Integer ethaccounttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_ethereum_account_detail.transType
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    private Integer transtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_ethereum_account_detail.amount
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    private String amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_ethereum_account_detail.gas
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    private String gas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_ethereum_account_detail.createTime
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_ethereum_account_detail.remark
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_ethereum_account_detail.id
     *
     * @return the value of ct_ethereum_account_detail.id
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_ethereum_account_detail.id
     *
     * @param id the value for ct_ethereum_account_detail.id
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_ethereum_account_detail.userId
     *
     * @return the value of ct_ethereum_account_detail.userId
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_ethereum_account_detail.userId
     *
     * @param userid the value for ct_ethereum_account_detail.userId
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_ethereum_account_detail.serialNo
     *
     * @return the value of ct_ethereum_account_detail.serialNo
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public String getSerialno() {
        return serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_ethereum_account_detail.serialNo
     *
     * @param serialno the value for ct_ethereum_account_detail.serialNo
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public void setSerialno(String serialno) {
        this.serialno = serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_ethereum_account_detail.ethAccount
     *
     * @return the value of ct_ethereum_account_detail.ethAccount
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public String getEthaccount() {
        return ethaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_ethereum_account_detail.ethAccount
     *
     * @param ethaccount the value for ct_ethereum_account_detail.ethAccount
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public void setEthaccount(String ethaccount) {
        this.ethaccount = ethaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_ethereum_account_detail.ethAccountType
     *
     * @return the value of ct_ethereum_account_detail.ethAccountType
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public Integer getEthaccounttype() {
        return ethaccounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_ethereum_account_detail.ethAccountType
     *
     * @param ethaccounttype the value for ct_ethereum_account_detail.ethAccountType
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public void setEthaccounttype(Integer ethaccounttype) {
        this.ethaccounttype = ethaccounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_ethereum_account_detail.transType
     *
     * @return the value of ct_ethereum_account_detail.transType
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public Integer getTranstype() {
        return transtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_ethereum_account_detail.transType
     *
     * @param transtype the value for ct_ethereum_account_detail.transType
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public void setTranstype(Integer transtype) {
        this.transtype = transtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_ethereum_account_detail.amount
     *
     * @return the value of ct_ethereum_account_detail.amount
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_ethereum_account_detail.amount
     *
     * @param amount the value for ct_ethereum_account_detail.amount
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_ethereum_account_detail.gas
     *
     * @return the value of ct_ethereum_account_detail.gas
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public String getGas() {
        return gas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_ethereum_account_detail.gas
     *
     * @param gas the value for ct_ethereum_account_detail.gas
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public void setGas(String gas) {
        this.gas = gas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_ethereum_account_detail.createTime
     *
     * @return the value of ct_ethereum_account_detail.createTime
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_ethereum_account_detail.createTime
     *
     * @param createtime the value for ct_ethereum_account_detail.createTime
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_ethereum_account_detail.remark
     *
     * @return the value of ct_ethereum_account_detail.remark
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_ethereum_account_detail.remark
     *
     * @param remark the value for ct_ethereum_account_detail.remark
     *
     * @mbg.generated Sat Aug 11 12:12:00 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}