package com.dce.business.entity.travel;

public class TravelPathDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_travel_path.pathid
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    private Integer pathid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_travel_path.linename
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    private String linename;
    

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_travel_path.state
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_travel_path.remake
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    private String remake;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_travel_path.pathid
     *
     * @return the value of ct_travel_path.pathid
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    public Integer getPathid() {
        return pathid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_travel_path.pathid
     *
     * @param pathid the value for ct_travel_path.pathid
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    public void setPathid(Integer pathid) {
        this.pathid = pathid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_travel_path.linename
     *
     * @return the value of ct_travel_path.linename
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    public String getLinename() {
        return linename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_travel_path.linename
     *
     * @param linename the value for ct_travel_path.linename
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    public void setLinename(String linename) {
        this.linename = linename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_travel_path.state
     *
     * @return the value of ct_travel_path.state
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_travel_path.state
     *
     * @param state the value for ct_travel_path.state
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_travel_path.remake
     *
     * @return the value of ct_travel_path.remake
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    public String getRemake() {
        return remake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_travel_path.remake
     *
     * @param remake the value for ct_travel_path.remake
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    public void setRemake(String remake) {
        this.remake = remake;
    }
}