package com.dce.business.dao.user;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dce.business.entity.user.UserAddressDo;

public interface IUserAddressDao {
	

   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_address
     *
     * @mbg.generated Sat Aug 18 18:26:36 CST 2018
     */
    int deleteByPrimaryKey(Integer addressid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_address
     *
     * @mbg.generated Sat Aug 18 18:26:36 CST 2018
     */
    int insert(UserAddressDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_address
     *
     * @mbg.generated Sat Aug 18 18:26:36 CST 2018
     */
    int insertSelective(UserAddressDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_address
     *
     * @mbg.generated Sat Aug 18 18:26:36 CST 2018
     */
    List<UserAddressDo> selectByUserId(@Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_address
     *
     * @mbg.generated Sat Aug 18 18:26:36 CST 2018
     */
    UserAddressDo selectByPrimaryKey(Integer addressid);

   

   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_address
     *
     * @mbg.generated Sat Aug 18 18:26:36 CST 2018
     */
    int updateByPrimaryKeySelective(UserAddressDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_address
     *
     * @mbg.generated Sat Aug 18 18:26:36 CST 2018
     */
    int updateByPrimaryKey(UserAddressDo record);

    
}