package com.dce.business.dao.travel;

import com.dce.business.entity.travel.TravelDo;
import com.dce.business.entity.travel.TravelDoExample;
import com.dce.business.entity.travel.TravelPathDo;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TravelDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Thu Aug 09 21:14:24 CST 2018
     */
    long countByExample(TravelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Thu Aug 09 21:14:24 CST 2018
     */
    int deleteByExample(TravelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Thu Aug 09 21:14:24 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Thu Aug 09 21:14:24 CST 2018
     */
    int insert(TravelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Thu Aug 09 21:14:24 CST 2018
     */
    int insertSelective(TravelDo record);
    
    int ravelRevokeById(Integer applyTravelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Thu Aug 09 21:14:24 CST 2018
     */
    List<TravelDo> selectByExample(TravelDoExample example);
    
    List<TravelDo> selectByUserId(Integer userid);
    
    List<TravelDo> queryListPage(Map<String, Object> param);
    
    
    int updateapplyStateById(Integer applyTravelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Thu Aug 09 21:14:24 CST 2018
     */
    TravelDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Thu Aug 09 21:14:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") TravelDo record, @Param("example") TravelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Thu Aug 09 21:14:24 CST 2018
     */
    int updateByExample(@Param("record") TravelDo record, @Param("example") TravelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Thu Aug 09 21:14:24 CST 2018
     */
    int updateByPrimaryKeySelective(TravelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Thu Aug 09 21:14:24 CST 2018
     */
    int updateByPrimaryKey(TravelDo record);
}