package com.dce.business.dao.travel;

import com.dce.business.entity.notice.NoticeDo;
import com.dce.business.entity.travel.TravelPathDo;
import com.dce.business.entity.travel.travelPathExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TravelPathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    long countByExample(travelPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int deleteByExample(travelPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int deleteByPrimaryKey(Integer pathid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int insert(TravelPathDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int insertSelective(TravelPathDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    List<TravelPathDo> selectByExample(travelPathExample example);
    
    
    List<TravelPathDo> selectPathAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    TravelPathDo selectByPrimaryKey(Integer pathid);
    
    List<TravelPathDo> queryListPage(Map<String, Object> param);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") TravelPathDo record, @Param("example") travelPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int updateByExample(@Param("record") TravelPathDo record, @Param("example") travelPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int updateByPrimaryKeySelective(TravelPathDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int updateByPrimaryKey(TravelPathDo record);
}