package com.dce.business.entity.order;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public OrderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andOrderidIsNull() {
			addCriterion("orderId is null");
			return (Criteria) this;
		}

		public Criteria andOrderidIsNotNull() {
			addCriterion("orderId is not null");
			return (Criteria) this;
		}

		public Criteria andOrderidEqualTo(Long value) {
			addCriterion("orderId =", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidNotEqualTo(Long value) {
			addCriterion("orderId <>", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidGreaterThan(Long value) {
			addCriterion("orderId >", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidGreaterThanOrEqualTo(Long value) {
			addCriterion("orderId >=", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidLessThan(Long value) {
			addCriterion("orderId <", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidLessThanOrEqualTo(Long value) {
			addCriterion("orderId <=", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidIn(List<Long> values) {
			addCriterion("orderId in", values, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidNotIn(List<Long> values) {
			addCriterion("orderId not in", values, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidBetween(Long value1, Long value2) {
			addCriterion("orderId between", value1, value2, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidNotBetween(Long value1, Long value2) {
			addCriterion("orderId not between", value1, value2, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrdercodeIsNull() {
			addCriterion("orderCode is null");
			return (Criteria) this;
		}

		public Criteria andOrdercodeIsNotNull() {
			addCriterion("orderCode is not null");
			return (Criteria) this;
		}

		public Criteria andOrdercodeEqualTo(String value) {
			addCriterion("orderCode =", value, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeNotEqualTo(String value) {
			addCriterion("orderCode <>", value, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeGreaterThan(String value) {
			addCriterion("orderCode >", value, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeGreaterThanOrEqualTo(String value) {
			addCriterion("orderCode >=", value, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeLessThan(String value) {
			addCriterion("orderCode <", value, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeLessThanOrEqualTo(String value) {
			addCriterion("orderCode <=", value, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeLike(String value) {
			addCriterion("orderCode like", value, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeNotLike(String value) {
			addCriterion("orderCode not like", value, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeIn(List<String> values) {
			addCriterion("orderCode in", values, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeNotIn(List<String> values) {
			addCriterion("orderCode not in", values, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeBetween(String value1, String value2) {
			addCriterion("orderCode between", value1, value2, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeNotBetween(String value1, String value2) {
			addCriterion("orderCode not between", value1, value2, "ordercode");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("userId is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("userId is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(Integer value) {
			addCriterion("userId =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(Integer value) {
			addCriterion("userId <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(Integer value) {
			addCriterion("userId >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("userId >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(Integer value) {
			addCriterion("userId <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(Integer value) {
			addCriterion("userId <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<Integer> values) {
			addCriterion("userId in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<Integer> values) {
			addCriterion("userId not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(Integer value1, Integer value2) {
			addCriterion("userId between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(Integer value1, Integer value2) {
			addCriterion("userId not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andQtyIsNull() {
			addCriterion("qty is null");
			return (Criteria) this;
		}

		public Criteria andQtyIsNotNull() {
			addCriterion("qty is not null");
			return (Criteria) this;
		}

		public Criteria andQtyEqualTo(BigDecimal value) {
			addCriterion("qty =", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyNotEqualTo(BigDecimal value) {
			addCriterion("qty <>", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyGreaterThan(BigDecimal value) {
			addCriterion("qty >", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("qty >=", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyLessThan(BigDecimal value) {
			addCriterion("qty <", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyLessThanOrEqualTo(BigDecimal value) {
			addCriterion("qty <=", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyIn(List<BigDecimal> values) {
			addCriterion("qty in", values, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyNotIn(List<BigDecimal> values) {
			addCriterion("qty not in", values, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("qty between", value1, value2, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("qty not between", value1, value2, "qty");
			return (Criteria) this;
		}

		public Criteria andTotalpriceIsNull() {
			addCriterion("totalPrice is null");
			return (Criteria) this;
		}

		public Criteria andTotalpriceIsNotNull() {
			addCriterion("totalPrice is not null");
			return (Criteria) this;
		}

		public Criteria andTotalpriceEqualTo(BigDecimal value) {
			addCriterion("totalPrice =", value, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceNotEqualTo(BigDecimal value) {
			addCriterion("totalPrice <>", value, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceGreaterThan(BigDecimal value) {
			addCriterion("totalPrice >", value, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("totalPrice >=", value, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceLessThan(BigDecimal value) {
			addCriterion("totalPrice <", value, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("totalPrice <=", value, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceIn(List<BigDecimal> values) {
			addCriterion("totalPrice in", values, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceNotIn(List<BigDecimal> values) {
			addCriterion("totalPrice not in", values, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("totalPrice between", value1, value2, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("totalPrice not between", value1, value2, "totalprice");
			return (Criteria) this;
		}

		public Criteria andRecaddressIsNull() {
			addCriterion("recAddress is null");
			return (Criteria) this;
		}

		public Criteria andRecaddressIsNotNull() {
			addCriterion("recAddress is not null");
			return (Criteria) this;
		}

		public Criteria andRecaddressEqualTo(String value) {
			addCriterion("recAddress =", value, "recaddress");
			return (Criteria) this;
		}

		public Criteria andRecaddressNotEqualTo(String value) {
			addCriterion("recAddress <>", value, "recaddress");
			return (Criteria) this;
		}

		public Criteria andRecaddressGreaterThan(String value) {
			addCriterion("recAddress >", value, "recaddress");
			return (Criteria) this;
		}

		public Criteria andRecaddressGreaterThanOrEqualTo(String value) {
			addCriterion("recAddress >=", value, "recaddress");
			return (Criteria) this;
		}

		public Criteria andRecaddressLessThan(String value) {
			addCriterion("recAddress <", value, "recaddress");
			return (Criteria) this;
		}

		public Criteria andRecaddressLessThanOrEqualTo(String value) {
			addCriterion("recAddress <=", value, "recaddress");
			return (Criteria) this;
		}

		public Criteria andRecaddressLike(String value) {
			addCriterion("recAddress like", value, "recaddress");
			return (Criteria) this;
		}

		public Criteria andRecaddressNotLike(String value) {
			addCriterion("recAddress not like", value, "recaddress");
			return (Criteria) this;
		}

		public Criteria andRecaddressIn(List<String> values) {
			addCriterion("recAddress in", values, "recaddress");
			return (Criteria) this;
		}

		public Criteria andRecaddressNotIn(List<String> values) {
			addCriterion("recAddress not in", values, "recaddress");
			return (Criteria) this;
		}

		public Criteria andRecaddressBetween(String value1, String value2) {
			addCriterion("recAddress between", value1, value2, "recaddress");
			return (Criteria) this;
		}

		public Criteria andRecaddressNotBetween(String value1, String value2) {
			addCriterion("recAddress not between", value1, value2, "recaddress");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("createTime is null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("createTime is not null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeEqualTo(Date value) {
			addCriterion("createTime =", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotEqualTo(Date value) {
			addCriterion("createTime <>", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThan(Date value) {
			addCriterion("createTime >", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("createTime >=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThan(Date value) {
			addCriterion("createTime <", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
			addCriterion("createTime <=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIn(List<Date> values) {
			addCriterion("createTime in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotIn(List<Date> values) {
			addCriterion("createTime not in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeBetween(Date value1, Date value2) {
			addCriterion("createTime between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
			addCriterion("createTime not between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andOrderstatusIsNull() {
			addCriterion("orderStatus is null");
			return (Criteria) this;
		}

		public Criteria andOrderstatusIsNotNull() {
			addCriterion("orderStatus is not null");
			return (Criteria) this;
		}

		public Criteria andOrderstatusEqualTo(Integer value) {
			addCriterion("orderStatus =", value, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusNotEqualTo(Integer value) {
			addCriterion("orderStatus <>", value, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusGreaterThan(Integer value) {
			addCriterion("orderStatus >", value, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("orderStatus >=", value, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusLessThan(Integer value) {
			addCriterion("orderStatus <", value, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusLessThanOrEqualTo(Integer value) {
			addCriterion("orderStatus <=", value, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusIn(List<Integer> values) {
			addCriterion("orderStatus in", values, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusNotIn(List<Integer> values) {
			addCriterion("orderStatus not in", values, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusBetween(Integer value1, Integer value2) {
			addCriterion("orderStatus between", value1, value2, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusNotBetween(Integer value1, Integer value2) {
			addCriterion("orderStatus not between", value1, value2, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andPaystatusIsNull() {
			addCriterion("payStatus is null");
			return (Criteria) this;
		}

		public Criteria andPaystatusIsNotNull() {
			addCriterion("payStatus is not null");
			return (Criteria) this;
		}

		public Criteria andPaystatusEqualTo(Integer value) {
			addCriterion("payStatus =", value, "paystatus");
			return (Criteria) this;
		}

		public Criteria andPaystatusNotEqualTo(Integer value) {
			addCriterion("payStatus <>", value, "paystatus");
			return (Criteria) this;
		}

		public Criteria andPaystatusGreaterThan(Integer value) {
			addCriterion("payStatus >", value, "paystatus");
			return (Criteria) this;
		}

		public Criteria andPaystatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("payStatus >=", value, "paystatus");
			return (Criteria) this;
		}

		public Criteria andPaystatusLessThan(Integer value) {
			addCriterion("payStatus <", value, "paystatus");
			return (Criteria) this;
		}

		public Criteria andPaystatusLessThanOrEqualTo(Integer value) {
			addCriterion("payStatus <=", value, "paystatus");
			return (Criteria) this;
		}

		public Criteria andPaystatusIn(List<Integer> values) {
			addCriterion("payStatus in", values, "paystatus");
			return (Criteria) this;
		}

		public Criteria andPaystatusNotIn(List<Integer> values) {
			addCriterion("payStatus not in", values, "paystatus");
			return (Criteria) this;
		}

		public Criteria andPaystatusBetween(Integer value1, Integer value2) {
			addCriterion("payStatus between", value1, value2, "paystatus");
			return (Criteria) this;
		}

		public Criteria andPaystatusNotBetween(Integer value1, Integer value2) {
			addCriterion("payStatus not between", value1, value2, "paystatus");
			return (Criteria) this;
		}

		public Criteria andPaytimeIsNull() {
			addCriterion("payTime is null");
			return (Criteria) this;
		}

		public Criteria andPaytimeIsNotNull() {
			addCriterion("payTime is not null");
			return (Criteria) this;
		}

		public Criteria andPaytimeEqualTo(Date value) {
			addCriterion("payTime =", value, "paytime");
			return (Criteria) this;
		}

		public Criteria andPaytimeNotEqualTo(Date value) {
			addCriterion("payTime <>", value, "paytime");
			return (Criteria) this;
		}

		public Criteria andPaytimeGreaterThan(Date value) {
			addCriterion("payTime >", value, "paytime");
			return (Criteria) this;
		}

		public Criteria andPaytimeGreaterThanOrEqualTo(Date value) {
			addCriterion("payTime >=", value, "paytime");
			return (Criteria) this;
		}

		public Criteria andPaytimeLessThan(Date value) {
			addCriterion("payTime <", value, "paytime");
			return (Criteria) this;
		}

		public Criteria andPaytimeLessThanOrEqualTo(Date value) {
			addCriterion("payTime <=", value, "paytime");
			return (Criteria) this;
		}

		public Criteria andPaytimeIn(List<Date> values) {
			addCriterion("payTime in", values, "paytime");
			return (Criteria) this;
		}

		public Criteria andPaytimeNotIn(List<Date> values) {
			addCriterion("payTime not in", values, "paytime");
			return (Criteria) this;
		}

		public Criteria andPaytimeBetween(Date value1, Date value2) {
			addCriterion("payTime between", value1, value2, "paytime");
			return (Criteria) this;
		}

		public Criteria andPaytimeNotBetween(Date value1, Date value2) {
			addCriterion("payTime not between", value1, value2, "paytime");
			return (Criteria) this;
		}

		public Criteria andOrdertypeIsNull() {
			addCriterion("orderType is null");
			return (Criteria) this;
		}

		public Criteria andOrdertypeIsNotNull() {
			addCriterion("orderType is not null");
			return (Criteria) this;
		}

		public Criteria andOrdertypeEqualTo(Integer value) {
			addCriterion("orderType =", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeNotEqualTo(Integer value) {
			addCriterion("orderType <>", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeGreaterThan(Integer value) {
			addCriterion("orderType >", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("orderType >=", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeLessThan(Integer value) {
			addCriterion("orderType <", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeLessThanOrEqualTo(Integer value) {
			addCriterion("orderType <=", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeIn(List<Integer> values) {
			addCriterion("orderType in", values, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeNotIn(List<Integer> values) {
			addCriterion("orderType not in", values, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeBetween(Integer value1, Integer value2) {
			addCriterion("orderType between", value1, value2, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeNotBetween(Integer value1, Integer value2) {
			addCriterion("orderType not between", value1, value2, "ordertype");
			return (Criteria) this;
		}

		public Criteria andMatchorderidIsNull() {
			addCriterion("matchOrderId is null");
			return (Criteria) this;
		}

		public Criteria andMatchorderidIsNotNull() {
			addCriterion("matchOrderId is not null");
			return (Criteria) this;
		}

		public Criteria andMatchorderidEqualTo(Long value) {
			addCriterion("matchOrderId =", value, "matchorderid");
			return (Criteria) this;
		}

		public Criteria andMatchorderidNotEqualTo(Long value) {
			addCriterion("matchOrderId <>", value, "matchorderid");
			return (Criteria) this;
		}

		public Criteria andMatchorderidGreaterThan(Long value) {
			addCriterion("matchOrderId >", value, "matchorderid");
			return (Criteria) this;
		}

		public Criteria andMatchorderidGreaterThanOrEqualTo(Long value) {
			addCriterion("matchOrderId >=", value, "matchorderid");
			return (Criteria) this;
		}

		public Criteria andMatchorderidLessThan(Long value) {
			addCriterion("matchOrderId <", value, "matchorderid");
			return (Criteria) this;
		}

		public Criteria andMatchorderidLessThanOrEqualTo(Long value) {
			addCriterion("matchOrderId <=", value, "matchorderid");
			return (Criteria) this;
		}

		public Criteria andMatchorderidIn(List<Long> values) {
			addCriterion("matchOrderId in", values, "matchorderid");
			return (Criteria) this;
		}

		public Criteria andMatchorderidNotIn(List<Long> values) {
			addCriterion("matchOrderId not in", values, "matchorderid");
			return (Criteria) this;
		}

		public Criteria andMatchorderidBetween(Long value1, Long value2) {
			addCriterion("matchOrderId between", value1, value2, "matchorderid");
			return (Criteria) this;
		}

		public Criteria andMatchorderidNotBetween(Long value1, Long value2) {
			addCriterion("matchOrderId not between", value1, value2, "matchorderid");
			return (Criteria) this;
		}

		public Criteria andSalqtyIsNull() {
			addCriterion("salqty is null");
			return (Criteria) this;
		}

		public Criteria andSalqtyIsNotNull() {
			addCriterion("salqty is not null");
			return (Criteria) this;
		}

		public Criteria andSalqtyEqualTo(BigDecimal value) {
			addCriterion("salqty =", value, "salqty");
			return (Criteria) this;
		}

		public Criteria andSalqtyNotEqualTo(BigDecimal value) {
			addCriterion("salqty <>", value, "salqty");
			return (Criteria) this;
		}

		public Criteria andSalqtyGreaterThan(BigDecimal value) {
			addCriterion("salqty >", value, "salqty");
			return (Criteria) this;
		}

		public Criteria andSalqtyGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("salqty >=", value, "salqty");
			return (Criteria) this;
		}

		public Criteria andSalqtyLessThan(BigDecimal value) {
			addCriterion("salqty <", value, "salqty");
			return (Criteria) this;
		}

		public Criteria andSalqtyLessThanOrEqualTo(BigDecimal value) {
			addCriterion("salqty <=", value, "salqty");
			return (Criteria) this;
		}

		public Criteria andSalqtyIn(List<BigDecimal> values) {
			addCriterion("salqty in", values, "salqty");
			return (Criteria) this;
		}

		public Criteria andSalqtyNotIn(List<BigDecimal> values) {
			addCriterion("salqty not in", values, "salqty");
			return (Criteria) this;
		}

		public Criteria andSalqtyBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("salqty between", value1, value2, "salqty");
			return (Criteria) this;
		}

		public Criteria andSalqtyNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("salqty not between", value1, value2, "salqty");
			return (Criteria) this;
		}

		public Criteria andAccounttypeIsNull() {
			addCriterion("accountType is null");
			return (Criteria) this;
		}

		public Criteria andAccounttypeIsNotNull() {
			addCriterion("accountType is not null");
			return (Criteria) this;
		}

		public Criteria andAccounttypeEqualTo(String value) {
			addCriterion("accountType =", value, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeNotEqualTo(String value) {
			addCriterion("accountType <>", value, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeGreaterThan(String value) {
			addCriterion("accountType >", value, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeGreaterThanOrEqualTo(String value) {
			addCriterion("accountType >=", value, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeLessThan(String value) {
			addCriterion("accountType <", value, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeLessThanOrEqualTo(String value) {
			addCriterion("accountType <=", value, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeLike(String value) {
			addCriterion("accountType like", value, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeNotLike(String value) {
			addCriterion("accountType not like", value, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeIn(List<String> values) {
			addCriterion("accountType in", values, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeNotIn(List<String> values) {
			addCriterion("accountType not in", values, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeBetween(String value1, String value2) {
			addCriterion("accountType between", value1, value2, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeNotBetween(String value1, String value2) {
			addCriterion("accountType not between", value1, value2, "accounttype");
			return (Criteria) this;
		}

		public Criteria andGoodsidIsNull() {
			addCriterion("goodsId is null");
			return (Criteria) this;
		}

		public Criteria andGoodsidIsNotNull() {
			addCriterion("goodsId is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsidEqualTo(Long value) {
			addCriterion("goodsId =", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidNotEqualTo(Long value) {
			addCriterion("goodsId <>", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidGreaterThan(Long value) {
			addCriterion("goodsId >", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidGreaterThanOrEqualTo(Long value) {
			addCriterion("goodsId >=", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidLessThan(Long value) {
			addCriterion("goodsId <", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidLessThanOrEqualTo(Long value) {
			addCriterion("goodsId <=", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidIn(List<Long> values) {
			addCriterion("goodsId in", values, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidNotIn(List<Long> values) {
			addCriterion("goodsId not in", values, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidBetween(Long value1, Long value2) {
			addCriterion("goodsId between", value1, value2, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidNotBetween(Long value1, Long value2) {
			addCriterion("goodsId not between", value1, value2, "goodsid");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Long value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Long value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Long value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Long value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Long value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Long value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Long> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Long> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Long value1, Long value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Long value1, Long value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andAddressidIsNull() {
			addCriterion("addressId is null");
			return (Criteria) this;
		}

		public Criteria andAddressidIsNotNull() {
			addCriterion("addressId is not null");
			return (Criteria) this;
		}

		public Criteria andAddressidEqualTo(Integer value) {
			addCriterion("addressId =", value, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidNotEqualTo(Integer value) {
			addCriterion("addressId <>", value, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidGreaterThan(Integer value) {
			addCriterion("addressId >", value, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidGreaterThanOrEqualTo(Integer value) {
			addCriterion("addressId >=", value, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidLessThan(Integer value) {
			addCriterion("addressId <", value, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidLessThanOrEqualTo(Integer value) {
			addCriterion("addressId <=", value, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidIn(List<Integer> values) {
			addCriterion("addressId in", values, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidNotIn(List<Integer> values) {
			addCriterion("addressId not in", values, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidBetween(Integer value1, Integer value2) {
			addCriterion("addressId between", value1, value2, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidNotBetween(Integer value1, Integer value2) {
			addCriterion("addressId not between", value1, value2, "addressid");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ct_order
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 07 12:15:42 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}