package com.dce.business.entity.district;

public class Regionalawards {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regionalawards.rewardsAreaId
     *
     * @mbg.generated Wed Aug 22 09:57:21 CST 2018
     */
    private Integer rewardsareaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regionalawards.rewardBalance
     *
     * @mbg.generated Wed Aug 22 09:57:21 CST 2018
     */
    private String rewardbalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regionalawards.algebra
     *
     * @mbg.generated Wed Aug 22 09:57:21 CST 2018
     */
    private Integer algebra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regionalawards.remark
     *
     * @mbg.generated Wed Aug 22 09:57:21 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regionalawards.rewardsAreaId
     *
     * @return the value of regionalawards.rewardsAreaId
     *
     * @mbg.generated Wed Aug 22 09:57:21 CST 2018
     */
    public Integer getRewardsareaid() {
        return rewardsareaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regionalawards.rewardsAreaId
     *
     * @param rewardsareaid the value for regionalawards.rewardsAreaId
     *
     * @mbg.generated Wed Aug 22 09:57:21 CST 2018
     */
    public void setRewardsareaid(Integer rewardsareaid) {
        this.rewardsareaid = rewardsareaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regionalawards.rewardBalance
     *
     * @return the value of regionalawards.rewardBalance
     *
     * @mbg.generated Wed Aug 22 09:57:21 CST 2018
     */
    public String getRewardbalance() {
        return rewardbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regionalawards.rewardBalance
     *
     * @param rewardbalance the value for regionalawards.rewardBalance
     *
     * @mbg.generated Wed Aug 22 09:57:21 CST 2018
     */
    public void setRewardbalance(String rewardbalance) {
        this.rewardbalance = rewardbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regionalawards.algebra
     *
     * @return the value of regionalawards.algebra
     *
     * @mbg.generated Wed Aug 22 09:57:21 CST 2018
     */
    public Integer getAlgebra() {
        return algebra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regionalawards.algebra
     *
     * @param algebra the value for regionalawards.algebra
     *
     * @mbg.generated Wed Aug 22 09:57:21 CST 2018
     */
    public void setAlgebra(Integer algebra) {
        this.algebra = algebra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regionalawards.remark
     *
     * @return the value of regionalawards.remark
     *
     * @mbg.generated Wed Aug 22 09:57:21 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regionalawards.remark
     *
     * @param remark the value for regionalawards.remark
     *
     * @mbg.generated Wed Aug 22 09:57:21 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}