package com.dce.business.dao.order;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dce.business.entity.order.OrderAddressDo;

public interface IOrderAddressDao {
	

   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_address
     *
     * @mbg.generated Sat Aug 18 18:26:36 CST 2018
     */
    int deleteByPrimaryKey(Integer addressid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_address
     *
     * @mbg.generated Sat Aug 18 18:26:36 CST 2018
     */
    int insert(OrderAddressDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_address
     *
     * @mbg.generated Sat Aug 18 18:26:36 CST 2018
     */
    int insertSelective(OrderAddressDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_address
     *
     * @mbg.generated Sat Aug 18 18:26:36 CST 2018
     */
    List<OrderAddressDo> selectByUserId(@Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_address
     *
     * @mbg.generated Sat Aug 18 18:26:36 CST 2018
     */
    OrderAddressDo selectByPrimaryKey(Integer addressid);

   

   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_address
     *
     * @mbg.generated Sat Aug 18 18:26:36 CST 2018
     */
    int updateByPrimaryKeySelective(OrderAddressDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_address
     *
     * @mbg.generated Sat Aug 18 18:26:36 CST 2018
     */
    int updateByPrimaryKey(OrderAddressDo record);

    
}