package com.dce.business.entity.award;

import com.dce.business.common.enums.AccountType;
import com.dce.business.common.exception.BusinessException;

public class Awardlist {
    
    private Integer awardid;

    private Integer buyerLecel;

   
    private String p1Level0;
    
    public String getP1Level0Dipaly() {
		return converDiaply(p1Level0);
	}

	private String converDiaply(String p1Level02) {
		return  "level 0 级购买"+minQty +"到" +maxQty+"获的奖励公式等于 300+(n-1)*300"+"现金";
	}
	
	/**
	 * 根据配置 用 - 分隔 ，配置进什么账户类型，如果没有配置报错 配置格式： 1-wallet_travel-4人港澳游 表示 1次，旅游账户 奖励
	 * 4人港澳游 ， wallet_travel 查看{@link AccountType}
	 * 
	 * @param oneAward
	 * @return
	 */
	public static String getAccountTypeByAward(String[] awds) {
		if (awds.length < 2) {
			throw new BusinessException("购买者对应的奖励办法没有正确配置，请检查奖励办法的配置", "error-refereeAward-004");
		}
		return awds[1];
	}
	
	/**
	 * 根据用户等级获取配置字段
	 * @param level
	 * @return
	 */
	public String getAwardConfigByLevel(Byte level) {
		switch (level) {
		case 0:
			getP1Level0();
			break;
		case 1:
			getP1Level1();
			break;
		case 2:
			getP1Level2();
			break;
		case 3:
			getP1Level3();
			break;
		case 4:
			getP1Level4();
			break;
		}
		return "";
	}
	
	
	

	private String p1Level0Dipaly;

    
    private String p1Level1;

    
    private String p1Level2;

   
    private String p1Level3;

   
    private String p1Level4;

    
    private String p2Level0;

   
    private String p2Level1;

    private String p2Level2;

   
    private String p2Level3;

   
    private String p2Level4;

    
    private String buyerAward;

    
    private Integer buyQty;

    
    private Integer minQty;

    
    private Integer maxQty;

    
    public Integer getAwardid() {
        return awardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column awardlist.awardId
     *
     * @param awardid the value for awardlist.awardId
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public void setAwardid(Integer awardid) {
        this.awardid = awardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column awardlist.buyer_lecel
     *
     * @return the value of awardlist.buyer_lecel
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public Integer getBuyerLecel() {
        return buyerLecel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column awardlist.buyer_lecel
     *
     * @param buyerLecel the value for awardlist.buyer_lecel
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public void setBuyerLecel(Integer buyerLecel) {
        this.buyerLecel = buyerLecel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column awardlist.p1_level0
     *
     * @return the value of awardlist.p1_level0
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public String getP1Level0() {
        return p1Level0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column awardlist.p1_level0
     *
     * @param p1Level0 the value for awardlist.p1_level0
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public void setP1Level0(String p1Level0) {
        this.p1Level0 = p1Level0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column awardlist.p1_level1
     *
     * @return the value of awardlist.p1_level1
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public String getP1Level1() {
        return p1Level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column awardlist.p1_level1
     *
     * @param p1Level1 the value for awardlist.p1_level1
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public void setP1Level1(String p1Level1) {
        this.p1Level1 = p1Level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column awardlist.p1_level2
     *
     * @return the value of awardlist.p1_level2
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public String getP1Level2() {
        return p1Level2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column awardlist.p1_level2
     *
     * @param p1Level2 the value for awardlist.p1_level2
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public void setP1Level2(String p1Level2) {
        this.p1Level2 = p1Level2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column awardlist.p1_level3
     *
     * @return the value of awardlist.p1_level3
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public String getP1Level3() {
        return p1Level3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column awardlist.p1_level3
     *
     * @param p1Level3 the value for awardlist.p1_level3
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public void setP1Level3(String p1Level3) {
        this.p1Level3 = p1Level3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column awardlist.p1_level4
     *
     * @return the value of awardlist.p1_level4
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public String getP1Level4() {
        return p1Level4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column awardlist.p1_level4
     *
     * @param p1Level4 the value for awardlist.p1_level4
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public void setP1Level4(String p1Level4) {
        this.p1Level4 = p1Level4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column awardlist.p2_level0
     *
     * @return the value of awardlist.p2_level0
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public String getP2Level0() {
        return p2Level0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column awardlist.p2_level0
     *
     * @param p2Level0 the value for awardlist.p2_level0
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public void setP2Level0(String p2Level0) {
        this.p2Level0 = p2Level0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column awardlist.p2_level1
     *
     * @return the value of awardlist.p2_level1
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public String getP2Level1() {
        return p2Level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column awardlist.p2_level1
     *
     * @param p2Level1 the value for awardlist.p2_level1
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public void setP2Level1(String p2Level1) {
        this.p2Level1 = p2Level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column awardlist.p2_level2
     *
     * @return the value of awardlist.p2_level2
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public String getP2Level2() {
        return p2Level2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column awardlist.p2_level2
     *
     * @param p2Level2 the value for awardlist.p2_level2
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public void setP2Level2(String p2Level2) {
        this.p2Level2 = p2Level2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column awardlist.p2_level3
     *
     * @return the value of awardlist.p2_level3
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public String getP2Level3() {
        return p2Level3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column awardlist.p2_level3
     *
     * @param p2Level3 the value for awardlist.p2_level3
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public void setP2Level3(String p2Level3) {
        this.p2Level3 = p2Level3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column awardlist.p2_level4
     *
     * @return the value of awardlist.p2_level4
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public String getP2Level4() {
        return p2Level4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column awardlist.p2_level4
     *
     * @param p2Level4 the value for awardlist.p2_level4
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public void setP2Level4(String p2Level4) {
        this.p2Level4 = p2Level4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column awardlist.buyer_award
     *
     * @return the value of awardlist.buyer_award
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public String getBuyerAward() {
        return buyerAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column awardlist.buyer_award
     *
     * @param buyerAward the value for awardlist.buyer_award
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public void setBuyerAward(String buyerAward) {
        this.buyerAward = buyerAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column awardlist.buy_qty
     *
     * @return the value of awardlist.buy_qty
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public Integer getBuyQty() {
        return buyQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column awardlist.buy_qty
     *
     * @param buyQty the value for awardlist.buy_qty
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public void setBuyQty(Integer buyQty) {
        this.buyQty = buyQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column awardlist.min_qty
     *
     * @return the value of awardlist.min_qty
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public Integer getMinQty() {
        return minQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column awardlist.min_qty
     *
     * @param minQty the value for awardlist.min_qty
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public void setMinQty(Integer minQty) {
        this.minQty = minQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column awardlist.max_qty
     *
     * @return the value of awardlist.max_qty
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public Integer getMaxQty() {
        return maxQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column awardlist.max_qty
     *
     * @param maxQty the value for awardlist.max_qty
     *
     * @mbg.generated Tue Aug 21 11:02:38 CST 2018
     */
    public void setMaxQty(Integer maxQty) {
        this.maxQty = maxQty;
    }
}