package com.dce.business.entity.award;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CtAwardExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ct_award
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ct_award
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ct_award
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_award
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public CtAwardExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_award
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_award
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_award
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_award
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_award
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_award
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_award
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_award
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_award
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_award
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ct_award
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAwardidIsNull() {
            addCriterion("awardId is null");
            return (Criteria) this;
        }

        public Criteria andAwardidIsNotNull() {
            addCriterion("awardId is not null");
            return (Criteria) this;
        }

        public Criteria andAwardidEqualTo(Integer value) {
            addCriterion("awardId =", value, "awardid");
            return (Criteria) this;
        }

        public Criteria andAwardidNotEqualTo(Integer value) {
            addCriterion("awardId <>", value, "awardid");
            return (Criteria) this;
        }

        public Criteria andAwardidGreaterThan(Integer value) {
            addCriterion("awardId >", value, "awardid");
            return (Criteria) this;
        }

        public Criteria andAwardidGreaterThanOrEqualTo(Integer value) {
            addCriterion("awardId >=", value, "awardid");
            return (Criteria) this;
        }

        public Criteria andAwardidLessThan(Integer value) {
            addCriterion("awardId <", value, "awardid");
            return (Criteria) this;
        }

        public Criteria andAwardidLessThanOrEqualTo(Integer value) {
            addCriterion("awardId <=", value, "awardid");
            return (Criteria) this;
        }

        public Criteria andAwardidIn(List<Integer> values) {
            addCriterion("awardId in", values, "awardid");
            return (Criteria) this;
        }

        public Criteria andAwardidNotIn(List<Integer> values) {
            addCriterion("awardId not in", values, "awardid");
            return (Criteria) this;
        }

        public Criteria andAwardidBetween(Integer value1, Integer value2) {
            addCriterion("awardId between", value1, value2, "awardid");
            return (Criteria) this;
        }

        public Criteria andAwardidNotBetween(Integer value1, Integer value2) {
            addCriterion("awardId not between", value1, value2, "awardid");
            return (Criteria) this;
        }

        public Criteria andAwardtimeIsNull() {
            addCriterion("awardTime is null");
            return (Criteria) this;
        }

        public Criteria andAwardtimeIsNotNull() {
            addCriterion("awardTime is not null");
            return (Criteria) this;
        }

        public Criteria andAwardtimeEqualTo(Date value) {
            addCriterion("awardTime =", value, "awardtime");
            return (Criteria) this;
        }

        public Criteria andAwardtimeNotEqualTo(Date value) {
            addCriterion("awardTime <>", value, "awardtime");
            return (Criteria) this;
        }

        public Criteria andAwardtimeGreaterThan(Date value) {
            addCriterion("awardTime >", value, "awardtime");
            return (Criteria) this;
        }

        public Criteria andAwardtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("awardTime >=", value, "awardtime");
            return (Criteria) this;
        }

        public Criteria andAwardtimeLessThan(Date value) {
            addCriterion("awardTime <", value, "awardtime");
            return (Criteria) this;
        }

        public Criteria andAwardtimeLessThanOrEqualTo(Date value) {
            addCriterion("awardTime <=", value, "awardtime");
            return (Criteria) this;
        }

        public Criteria andAwardtimeIn(List<Date> values) {
            addCriterion("awardTime in", values, "awardtime");
            return (Criteria) this;
        }

        public Criteria andAwardtimeNotIn(List<Date> values) {
            addCriterion("awardTime not in", values, "awardtime");
            return (Criteria) this;
        }

        public Criteria andAwardtimeBetween(Date value1, Date value2) {
            addCriterion("awardTime between", value1, value2, "awardtime");
            return (Criteria) this;
        }

        public Criteria andAwardtimeNotBetween(Date value1, Date value2) {
            addCriterion("awardTime not between", value1, value2, "awardtime");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andAwardmoneyIsNull() {
            addCriterion("awardMoney is null");
            return (Criteria) this;
        }

        public Criteria andAwardmoneyIsNotNull() {
            addCriterion("awardMoney is not null");
            return (Criteria) this;
        }

        public Criteria andAwardmoneyEqualTo(Double value) {
            addCriterion("awardMoney =", value, "awardmoney");
            return (Criteria) this;
        }

        public Criteria andAwardmoneyNotEqualTo(Double value) {
            addCriterion("awardMoney <>", value, "awardmoney");
            return (Criteria) this;
        }

        public Criteria andAwardmoneyGreaterThan(Double value) {
            addCriterion("awardMoney >", value, "awardmoney");
            return (Criteria) this;
        }

        public Criteria andAwardmoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("awardMoney >=", value, "awardmoney");
            return (Criteria) this;
        }

        public Criteria andAwardmoneyLessThan(Double value) {
            addCriterion("awardMoney <", value, "awardmoney");
            return (Criteria) this;
        }

        public Criteria andAwardmoneyLessThanOrEqualTo(Double value) {
            addCriterion("awardMoney <=", value, "awardmoney");
            return (Criteria) this;
        }

        public Criteria andAwardmoneyIn(List<Double> values) {
            addCriterion("awardMoney in", values, "awardmoney");
            return (Criteria) this;
        }

        public Criteria andAwardmoneyNotIn(List<Double> values) {
            addCriterion("awardMoney not in", values, "awardmoney");
            return (Criteria) this;
        }

        public Criteria andAwardmoneyBetween(Double value1, Double value2) {
            addCriterion("awardMoney between", value1, value2, "awardmoney");
            return (Criteria) this;
        }

        public Criteria andAwardmoneyNotBetween(Double value1, Double value2) {
            addCriterion("awardMoney not between", value1, value2, "awardmoney");
            return (Criteria) this;
        }

        public Criteria andAwardreasonIsNull() {
            addCriterion("awardReason is null");
            return (Criteria) this;
        }

        public Criteria andAwardreasonIsNotNull() {
            addCriterion("awardReason is not null");
            return (Criteria) this;
        }

        public Criteria andAwardreasonEqualTo(String value) {
            addCriterion("awardReason =", value, "awardreason");
            return (Criteria) this;
        }

        public Criteria andAwardreasonNotEqualTo(String value) {
            addCriterion("awardReason <>", value, "awardreason");
            return (Criteria) this;
        }

        public Criteria andAwardreasonGreaterThan(String value) {
            addCriterion("awardReason >", value, "awardreason");
            return (Criteria) this;
        }

        public Criteria andAwardreasonGreaterThanOrEqualTo(String value) {
            addCriterion("awardReason >=", value, "awardreason");
            return (Criteria) this;
        }

        public Criteria andAwardreasonLessThan(String value) {
            addCriterion("awardReason <", value, "awardreason");
            return (Criteria) this;
        }

        public Criteria andAwardreasonLessThanOrEqualTo(String value) {
            addCriterion("awardReason <=", value, "awardreason");
            return (Criteria) this;
        }

        public Criteria andAwardreasonLike(String value) {
            addCriterion("awardReason like", value, "awardreason");
            return (Criteria) this;
        }

        public Criteria andAwardreasonNotLike(String value) {
            addCriterion("awardReason not like", value, "awardreason");
            return (Criteria) this;
        }

        public Criteria andAwardreasonIn(List<String> values) {
            addCriterion("awardReason in", values, "awardreason");
            return (Criteria) this;
        }

        public Criteria andAwardreasonNotIn(List<String> values) {
            addCriterion("awardReason not in", values, "awardreason");
            return (Criteria) this;
        }

        public Criteria andAwardreasonBetween(String value1, String value2) {
            addCriterion("awardReason between", value1, value2, "awardreason");
            return (Criteria) this;
        }

        public Criteria andAwardreasonNotBetween(String value1, String value2) {
            addCriterion("awardReason not between", value1, value2, "awardreason");
            return (Criteria) this;
        }

        public Criteria andAwardusedstatusIsNull() {
            addCriterion("awardUsedStatus is null");
            return (Criteria) this;
        }

        public Criteria andAwardusedstatusIsNotNull() {
            addCriterion("awardUsedStatus is not null");
            return (Criteria) this;
        }

        public Criteria andAwardusedstatusEqualTo(Integer value) {
            addCriterion("awardUsedStatus =", value, "awardusedstatus");
            return (Criteria) this;
        }

        public Criteria andAwardusedstatusNotEqualTo(Integer value) {
            addCriterion("awardUsedStatus <>", value, "awardusedstatus");
            return (Criteria) this;
        }

        public Criteria andAwardusedstatusGreaterThan(Integer value) {
            addCriterion("awardUsedStatus >", value, "awardusedstatus");
            return (Criteria) this;
        }

        public Criteria andAwardusedstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("awardUsedStatus >=", value, "awardusedstatus");
            return (Criteria) this;
        }

        public Criteria andAwardusedstatusLessThan(Integer value) {
            addCriterion("awardUsedStatus <", value, "awardusedstatus");
            return (Criteria) this;
        }

        public Criteria andAwardusedstatusLessThanOrEqualTo(Integer value) {
            addCriterion("awardUsedStatus <=", value, "awardusedstatus");
            return (Criteria) this;
        }

        public Criteria andAwardusedstatusIn(List<Integer> values) {
            addCriterion("awardUsedStatus in", values, "awardusedstatus");
            return (Criteria) this;
        }

        public Criteria andAwardusedstatusNotIn(List<Integer> values) {
            addCriterion("awardUsedStatus not in", values, "awardusedstatus");
            return (Criteria) this;
        }

        public Criteria andAwardusedstatusBetween(Integer value1, Integer value2) {
            addCriterion("awardUsedStatus between", value1, value2, "awardusedstatus");
            return (Criteria) this;
        }

        public Criteria andAwardusedstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("awardUsedStatus not between", value1, value2, "awardusedstatus");
            return (Criteria) this;
        }

        public Criteria andAwardstatusIsNull() {
            addCriterion("awardStatus is null");
            return (Criteria) this;
        }

        public Criteria andAwardstatusIsNotNull() {
            addCriterion("awardStatus is not null");
            return (Criteria) this;
        }

        public Criteria andAwardstatusEqualTo(Integer value) {
            addCriterion("awardStatus =", value, "awardstatus");
            return (Criteria) this;
        }

        public Criteria andAwardstatusNotEqualTo(Integer value) {
            addCriterion("awardStatus <>", value, "awardstatus");
            return (Criteria) this;
        }

        public Criteria andAwardstatusGreaterThan(Integer value) {
            addCriterion("awardStatus >", value, "awardstatus");
            return (Criteria) this;
        }

        public Criteria andAwardstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("awardStatus >=", value, "awardstatus");
            return (Criteria) this;
        }

        public Criteria andAwardstatusLessThan(Integer value) {
            addCriterion("awardStatus <", value, "awardstatus");
            return (Criteria) this;
        }

        public Criteria andAwardstatusLessThanOrEqualTo(Integer value) {
            addCriterion("awardStatus <=", value, "awardstatus");
            return (Criteria) this;
        }

        public Criteria andAwardstatusIn(List<Integer> values) {
            addCriterion("awardStatus in", values, "awardstatus");
            return (Criteria) this;
        }

        public Criteria andAwardstatusNotIn(List<Integer> values) {
            addCriterion("awardStatus not in", values, "awardstatus");
            return (Criteria) this;
        }

        public Criteria andAwardstatusBetween(Integer value1, Integer value2) {
            addCriterion("awardStatus between", value1, value2, "awardstatus");
            return (Criteria) this;
        }

        public Criteria andAwardstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("awardStatus not between", value1, value2, "awardstatus");
            return (Criteria) this;
        }

        public Criteria andAwardtypeIsNull() {
            addCriterion("awardType is null");
            return (Criteria) this;
        }

        public Criteria andAwardtypeIsNotNull() {
            addCriterion("awardType is not null");
            return (Criteria) this;
        }

        public Criteria andAwardtypeEqualTo(Integer value) {
            addCriterion("awardType =", value, "awardtype");
            return (Criteria) this;
        }

        public Criteria andAwardtypeNotEqualTo(Integer value) {
            addCriterion("awardType <>", value, "awardtype");
            return (Criteria) this;
        }

        public Criteria andAwardtypeGreaterThan(Integer value) {
            addCriterion("awardType >", value, "awardtype");
            return (Criteria) this;
        }

        public Criteria andAwardtypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("awardType >=", value, "awardtype");
            return (Criteria) this;
        }

        public Criteria andAwardtypeLessThan(Integer value) {
            addCriterion("awardType <", value, "awardtype");
            return (Criteria) this;
        }

        public Criteria andAwardtypeLessThanOrEqualTo(Integer value) {
            addCriterion("awardType <=", value, "awardtype");
            return (Criteria) this;
        }

        public Criteria andAwardtypeIn(List<Integer> values) {
            addCriterion("awardType in", values, "awardtype");
            return (Criteria) this;
        }

        public Criteria andAwardtypeNotIn(List<Integer> values) {
            addCriterion("awardType not in", values, "awardtype");
            return (Criteria) this;
        }

        public Criteria andAwardtypeBetween(Integer value1, Integer value2) {
            addCriterion("awardType between", value1, value2, "awardtype");
            return (Criteria) this;
        }

        public Criteria andAwardtypeNotBetween(Integer value1, Integer value2) {
            addCriterion("awardType not between", value1, value2, "awardtype");
            return (Criteria) this;
        }

        public Criteria andAwardusedtimeIsNull() {
            addCriterion("awardUsedTime is null");
            return (Criteria) this;
        }

        public Criteria andAwardusedtimeIsNotNull() {
            addCriterion("awardUsedTime is not null");
            return (Criteria) this;
        }

        public Criteria andAwardusedtimeEqualTo(Date value) {
            addCriterion("awardUsedTime =", value, "awardusedtime");
            return (Criteria) this;
        }

        public Criteria andAwardusedtimeNotEqualTo(Date value) {
            addCriterion("awardUsedTime <>", value, "awardusedtime");
            return (Criteria) this;
        }

        public Criteria andAwardusedtimeGreaterThan(Date value) {
            addCriterion("awardUsedTime >", value, "awardusedtime");
            return (Criteria) this;
        }

        public Criteria andAwardusedtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("awardUsedTime >=", value, "awardusedtime");
            return (Criteria) this;
        }

        public Criteria andAwardusedtimeLessThan(Date value) {
            addCriterion("awardUsedTime <", value, "awardusedtime");
            return (Criteria) this;
        }

        public Criteria andAwardusedtimeLessThanOrEqualTo(Date value) {
            addCriterion("awardUsedTime <=", value, "awardusedtime");
            return (Criteria) this;
        }

        public Criteria andAwardusedtimeIn(List<Date> values) {
            addCriterion("awardUsedTime in", values, "awardusedtime");
            return (Criteria) this;
        }

        public Criteria andAwardusedtimeNotIn(List<Date> values) {
            addCriterion("awardUsedTime not in", values, "awardusedtime");
            return (Criteria) this;
        }

        public Criteria andAwardusedtimeBetween(Date value1, Date value2) {
            addCriterion("awardUsedTime between", value1, value2, "awardusedtime");
            return (Criteria) this;
        }

        public Criteria andAwardusedtimeNotBetween(Date value1, Date value2) {
            addCriterion("awardUsedTime not between", value1, value2, "awardusedtime");
            return (Criteria) this;
        }

        public Criteria andAwardupdatetimeIsNull() {
            addCriterion("awardUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andAwardupdatetimeIsNotNull() {
            addCriterion("awardUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andAwardupdatetimeEqualTo(Date value) {
            addCriterion("awardUpdateTime =", value, "awardupdatetime");
            return (Criteria) this;
        }

        public Criteria andAwardupdatetimeNotEqualTo(Date value) {
            addCriterion("awardUpdateTime <>", value, "awardupdatetime");
            return (Criteria) this;
        }

        public Criteria andAwardupdatetimeGreaterThan(Date value) {
            addCriterion("awardUpdateTime >", value, "awardupdatetime");
            return (Criteria) this;
        }

        public Criteria andAwardupdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("awardUpdateTime >=", value, "awardupdatetime");
            return (Criteria) this;
        }

        public Criteria andAwardupdatetimeLessThan(Date value) {
            addCriterion("awardUpdateTime <", value, "awardupdatetime");
            return (Criteria) this;
        }

        public Criteria andAwardupdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("awardUpdateTime <=", value, "awardupdatetime");
            return (Criteria) this;
        }

        public Criteria andAwardupdatetimeIn(List<Date> values) {
            addCriterion("awardUpdateTime in", values, "awardupdatetime");
            return (Criteria) this;
        }

        public Criteria andAwardupdatetimeNotIn(List<Date> values) {
            addCriterion("awardUpdateTime not in", values, "awardupdatetime");
            return (Criteria) this;
        }

        public Criteria andAwardupdatetimeBetween(Date value1, Date value2) {
            addCriterion("awardUpdateTime between", value1, value2, "awardupdatetime");
            return (Criteria) this;
        }

        public Criteria andAwardupdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("awardUpdateTime not between", value1, value2, "awardupdatetime");
            return (Criteria) this;
        }

        public Criteria andAwardcreatetimeIsNull() {
            addCriterion("awardCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andAwardcreatetimeIsNotNull() {
            addCriterion("awardCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andAwardcreatetimeEqualTo(Date value) {
            addCriterion("awardCreateTime =", value, "awardcreatetime");
            return (Criteria) this;
        }

        public Criteria andAwardcreatetimeNotEqualTo(Date value) {
            addCriterion("awardCreateTime <>", value, "awardcreatetime");
            return (Criteria) this;
        }

        public Criteria andAwardcreatetimeGreaterThan(Date value) {
            addCriterion("awardCreateTime >", value, "awardcreatetime");
            return (Criteria) this;
        }

        public Criteria andAwardcreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("awardCreateTime >=", value, "awardcreatetime");
            return (Criteria) this;
        }

        public Criteria andAwardcreatetimeLessThan(Date value) {
            addCriterion("awardCreateTime <", value, "awardcreatetime");
            return (Criteria) this;
        }

        public Criteria andAwardcreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("awardCreateTime <=", value, "awardcreatetime");
            return (Criteria) this;
        }

        public Criteria andAwardcreatetimeIn(List<Date> values) {
            addCriterion("awardCreateTime in", values, "awardcreatetime");
            return (Criteria) this;
        }

        public Criteria andAwardcreatetimeNotIn(List<Date> values) {
            addCriterion("awardCreateTime not in", values, "awardcreatetime");
            return (Criteria) this;
        }

        public Criteria andAwardcreatetimeBetween(Date value1, Date value2) {
            addCriterion("awardCreateTime between", value1, value2, "awardcreatetime");
            return (Criteria) this;
        }

        public Criteria andAwardcreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("awardCreateTime not between", value1, value2, "awardcreatetime");
            return (Criteria) this;
        }

        public Criteria andAwardoperationnameIsNull() {
            addCriterion("awardOperationName is null");
            return (Criteria) this;
        }

        public Criteria andAwardoperationnameIsNotNull() {
            addCriterion("awardOperationName is not null");
            return (Criteria) this;
        }

        public Criteria andAwardoperationnameEqualTo(String value) {
            addCriterion("awardOperationName =", value, "awardoperationname");
            return (Criteria) this;
        }

        public Criteria andAwardoperationnameNotEqualTo(String value) {
            addCriterion("awardOperationName <>", value, "awardoperationname");
            return (Criteria) this;
        }

        public Criteria andAwardoperationnameGreaterThan(String value) {
            addCriterion("awardOperationName >", value, "awardoperationname");
            return (Criteria) this;
        }

        public Criteria andAwardoperationnameGreaterThanOrEqualTo(String value) {
            addCriterion("awardOperationName >=", value, "awardoperationname");
            return (Criteria) this;
        }

        public Criteria andAwardoperationnameLessThan(String value) {
            addCriterion("awardOperationName <", value, "awardoperationname");
            return (Criteria) this;
        }

        public Criteria andAwardoperationnameLessThanOrEqualTo(String value) {
            addCriterion("awardOperationName <=", value, "awardoperationname");
            return (Criteria) this;
        }

        public Criteria andAwardoperationnameLike(String value) {
            addCriterion("awardOperationName like", value, "awardoperationname");
            return (Criteria) this;
        }

        public Criteria andAwardoperationnameNotLike(String value) {
            addCriterion("awardOperationName not like", value, "awardoperationname");
            return (Criteria) this;
        }

        public Criteria andAwardoperationnameIn(List<String> values) {
            addCriterion("awardOperationName in", values, "awardoperationname");
            return (Criteria) this;
        }

        public Criteria andAwardoperationnameNotIn(List<String> values) {
            addCriterion("awardOperationName not in", values, "awardoperationname");
            return (Criteria) this;
        }

        public Criteria andAwardoperationnameBetween(String value1, String value2) {
            addCriterion("awardOperationName between", value1, value2, "awardoperationname");
            return (Criteria) this;
        }

        public Criteria andAwardoperationnameNotBetween(String value1, String value2) {
            addCriterion("awardOperationName not between", value1, value2, "awardoperationname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ct_award
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 07 11:38:22 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ct_award
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}