package com.dce.business.entity.award;

import java.util.Date;

public class CtAward {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_award.awardId
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    private Integer awardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_award.awardTime
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    private Date awardtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_award.userId
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_award.awardMoney
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    private Double awardmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_award.awardReason
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    private String awardreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_award.awardUsedStatus
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    private Integer awardusedstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_award.awardStatus
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    private Integer awardstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_award.awardType
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    private Integer awardtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_award.awardUsedTime
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    private Date awardusedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_award.awardUpdateTime
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    private Date awardupdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_award.awardCreateTime
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    private Date awardcreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_award.awardOperationName
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    private String awardoperationname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_award.awardId
     *
     * @return the value of ct_award.awardId
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public Integer getAwardid() {
        return awardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_award.awardId
     *
     * @param awardid the value for ct_award.awardId
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public void setAwardid(Integer awardid) {
        this.awardid = awardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_award.awardTime
     *
     * @return the value of ct_award.awardTime
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public Date getAwardtime() {
        return awardtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_award.awardTime
     *
     * @param awardtime the value for ct_award.awardTime
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public void setAwardtime(Date awardtime) {
        this.awardtime = awardtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_award.userId
     *
     * @return the value of ct_award.userId
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_award.userId
     *
     * @param userid the value for ct_award.userId
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_award.awardMoney
     *
     * @return the value of ct_award.awardMoney
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public Double getAwardmoney() {
        return awardmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_award.awardMoney
     *
     * @param awardmoney the value for ct_award.awardMoney
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public void setAwardmoney(Double awardmoney) {
        this.awardmoney = awardmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_award.awardReason
     *
     * @return the value of ct_award.awardReason
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public String getAwardreason() {
        return awardreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_award.awardReason
     *
     * @param awardreason the value for ct_award.awardReason
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public void setAwardreason(String awardreason) {
        this.awardreason = awardreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_award.awardUsedStatus
     *
     * @return the value of ct_award.awardUsedStatus
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public Integer getAwardusedstatus() {
        return awardusedstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_award.awardUsedStatus
     *
     * @param awardusedstatus the value for ct_award.awardUsedStatus
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public void setAwardusedstatus(Integer awardusedstatus) {
        this.awardusedstatus = awardusedstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_award.awardStatus
     *
     * @return the value of ct_award.awardStatus
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public Integer getAwardstatus() {
        return awardstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_award.awardStatus
     *
     * @param awardstatus the value for ct_award.awardStatus
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public void setAwardstatus(Integer awardstatus) {
        this.awardstatus = awardstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_award.awardType
     *
     * @return the value of ct_award.awardType
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public Integer getAwardtype() {
        return awardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_award.awardType
     *
     * @param awardtype the value for ct_award.awardType
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public void setAwardtype(Integer awardtype) {
        this.awardtype = awardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_award.awardUsedTime
     *
     * @return the value of ct_award.awardUsedTime
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public Date getAwardusedtime() {
        return awardusedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_award.awardUsedTime
     *
     * @param awardusedtime the value for ct_award.awardUsedTime
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public void setAwardusedtime(Date awardusedtime) {
        this.awardusedtime = awardusedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_award.awardUpdateTime
     *
     * @return the value of ct_award.awardUpdateTime
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public Date getAwardupdatetime() {
        return awardupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_award.awardUpdateTime
     *
     * @param awardupdatetime the value for ct_award.awardUpdateTime
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public void setAwardupdatetime(Date awardupdatetime) {
        this.awardupdatetime = awardupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_award.awardCreateTime
     *
     * @return the value of ct_award.awardCreateTime
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public Date getAwardcreatetime() {
        return awardcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_award.awardCreateTime
     *
     * @param awardcreatetime the value for ct_award.awardCreateTime
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public void setAwardcreatetime(Date awardcreatetime) {
        this.awardcreatetime = awardcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_award.awardOperationName
     *
     * @return the value of ct_award.awardOperationName
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public String getAwardoperationname() {
        return awardoperationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_award.awardOperationName
     *
     * @param awardoperationname the value for ct_award.awardOperationName
     *
     * @mbg.generated Tue Aug 07 11:38:22 CST 2018
     */
    public void setAwardoperationname(String awardoperationname) {
        this.awardoperationname = awardoperationname;
    }
}